import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "next-themes";
import AuthRootProvider from "src/utils/providers/AuthRootProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"], // Add only the weights you need
  variable: "--font-roboto",
  style: ["normal", "italic"], // Optional: if you need italic support
});

export const metadata: Metadata = {
  title: "B4Boosting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      suppressHydrationWarning
         className={`${roboto.variable} antialiased`}
      >
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthRootProvider>
          {children}
           <Toaster position="top-center" />
           </AuthRootProvider>
        </ThemeProvider>
        
         
      </body>
    </html>
  );
}
